#ifndef MAP_H_INCLUDED
#define MAP_H_INCLUDED

#define TILE_FON_INDEX TILE_USERINDEX + 183
#define TILE_BORDER_INDEX TILE_USERINDEX + 162

#define TILE_BORDER_NONE TILE_BORDER_INDEX
#define TILE_BORDER_TOP TILE_BORDER_INDEX + 1
#define TILE_BORDER_TOP_END TILE_BORDER_TOP + 3
#define TILE_BORDER_DOWN TILE_BORDER_TOP_END + 2
#define TILE_BORDER_DOWN_END TILE_BORDER_DOWN + 3
#define TILE_BORDER_LEFT TILE_BORDER_DOWN_END + 2
#define TILE_BORDER_LEFT_END TILE_BORDER_LEFT + 3
#define TILE_BORDER_RIGHT TILE_BORDER_LEFT_END + 2
#define TILE_BORDER_RIGHT_END TILE_BORDER_RIGHT + 3

#define FON_NONE1 		TILE_FON_INDEX
#define FON_NONE2 		FON_NONE1		+ 4
#define FON_STONE 		FON_NONE2		+ 4
#define FON_BONE_HOR 	FON_STONE		+ 4
#define FON_BONE_VER	FON_BONE_HOR	+ 4
#define FON_HOUSE_1_LT	FON_BONE_VER	+ 4
#define FON_HOUSE_1_CT	FON_HOUSE_1_LT	+ 4
#define FON_HOUSE_1_RT	FON_HOUSE_1_CT	+ 4
#define FON_HOUSE_1_LC	FON_HOUSE_1_RT	+ 4
#define FON_HOUSE_1_CC	FON_HOUSE_1_LC	+ 4
#define FON_HOUSE_1_RC	FON_HOUSE_1_CC	+ 4
#define FON_HOUSE_1_LD	FON_HOUSE_1_RC	+ 4
#define FON_HOUSE_1_CD	FON_HOUSE_1_LD	+ 4
#define FON_HOUSE_1_RD	FON_HOUSE_1_CD	+ 4
#define FON_SKULL		FON_HOUSE_1_RD	+ 4
#define FON_NONE3		FON_SKULL		+ 4
#define FON_HOUSE_2_LT	FON_NONE3		+ 4
#define FON_HOUSE_2_CT	FON_HOUSE_2_LT	+ 4
#define FON_HOUSE_2_RT	FON_HOUSE_2_CT	+ 4
#define FON_HOUSE_2_LC	FON_HOUSE_2_RT	+ 4
#define FON_HOUSE_2_CC	FON_HOUSE_2_LC	+ 4
#define FON_HOUSE_2_RC	FON_HOUSE_2_CC	+ 4
#define FON_HOUSE_2_LD	FON_HOUSE_2_RC	+ 4
#define FON_HOUSE_2_CD	FON_HOUSE_2_LD	+ 4
#define FON_HOUSE_2_RD	FON_HOUSE_2_CD	+ 4
#define FON_HOUSE_3_LT	FON_HOUSE_2_RD	+ 4
#define FON_HOUSE_3_CT	FON_HOUSE_3_LT	+ 4
#define FON_HOUSE_3_RT	FON_HOUSE_3_CT	+ 4
#define FON_HOUSE_3_LC	FON_HOUSE_3_RT	+ 4
#define FON_HOUSE_3_CC	FON_HOUSE_3_LC	+ 4
#define FON_HOUSE_3_RC	FON_HOUSE_3_CC	+ 4
#define FON_HOUSE_3_LD	FON_HOUSE_3_RC	+ 4
#define FON_HOUSE_3_CD	FON_HOUSE_3_LD	+ 4
#define FON_HOUSE_3_RD	FON_HOUSE_3_CD	+ 4
#define FON_NONE4		FON_HOUSE_3_RD	+ 4
#define FON_HOUSE_3_CTT	FON_NONE4		+ 4

#define MAP_SIZE 2
#define MAP_SIZE2 4

#define MAP_ROW_MAX 23
#define MAP_ROW_OFFSET 4

#define MAP_ROW_START MAP_ROW_OFFSET + 1
#define MAP_ROW_END MAP_ROW_MAX + MAP_ROW_OFFSET + 1

#define BORDER_ROW_START MAP_ROW_OFFSET
#define BORDER_ROW_END MAP_ROW_MAX + MAP_ROW_OFFSET

#define MAP_COL_MAX 31
#define MAP_COL_OFFSET 0

#define MAP_COL_START MAP_COL_OFFSET + 1
#define MAP_COL_END MAP_COL_MAX + MAP_COL_OFFSET + 1

#define BORDER_COL_START MAP_COL_OFFSET
#define BORDER_COL_END MAP_COL_MAX + MAP_COL_OFFSET

#define MIN(i,j) ((i > j) ? j : i)

#define TILE_8x8 1
#define TILE_16x16 2
#define TILE_48x48 6

#define PATERN2 2
#define PATERN4	4

typedef struct
{
	u32	type;
	u8	go;
}		t_map;

#endif // MAP_H_INCLUDED
